#! /bin/sh

# Keyboard control
sxhkd &

# Three desktops
bspc monitor ^1 -d I II III

# Other config (TODO: trim down)
bspc config border_width        	2
bspc config window_gap          	12
bspc config split_ratio          	0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_by_distance    	true
bspc config focus_follows_pointer	true
bspc config history_aware_focus  	true

# Start in monacle mode
bspc desktop -l next

# Start chromium
compton -b
unclutter &
chromium --app="http://trouble.physics.byu.edu/display/"
