#! /bin/sh

#sxhkd &
#compton &
#conky &
#feh --bg-scale /home/cole/Pictures/ivysaur_hd_wallpaper_by_goddessofmayhem-d4tjcjk.jpg &

chromium --app http://trouble.physics.byu.edu/display/

bspc config -m ^2 right_padding		230
bspc config border_width        	2
bspc config window_gap          	12

bspc config split_ratio          	0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_by_distance    	true
bspc config focus_follows_pointer	true
bspc config history_aware_focus  	true

bspc monitor ^1 -d I II III IV
